version: '3.8'

services:
  nuxt-app-dev:
    image: nuxt-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nuxt-dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    expose:
      - "3000"
    ports:
      - "3001:3000"
    command: npm run dev